# -*- coding: utf-8 -*-
"""inference

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sYX6kPX_F_EJS93wXBPbeuzx6GVRIDGg
"""

import pandas as pd
import joblib

model = joblib.load('models/anomaly_model.pkl')

def predict_failure(data):
    return model.predict(data)

if __name__ == '__main__':
    test_data = pd.read_csv('data/test_FD001.txt', delim_whitespace=True, header=None)
    print(predict_failure(test_data.head(1)))