# -*- coding: utf-8 -*-
"""model_training

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sYX6kPX_F_EJS93wXBPbeuzx6GVRIDGg
"""

import pandas as pd
import numpy as np
from sklearn.ensemble import IsolationForest, RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

# Load dataset
df_train = pd.read_csv('data/train_FD001.txt', delim_whitespace=True, header=None)
df_train.columns = ["unit", "time", "op1", "op2", "op3"] + [f"sensor_{i}" for i in range(1, 22)]

# Feature selection
X = df_train.drop(columns=['unit', 'time'])
y = (df_train['sensor_21'] > df_train['sensor_21'].mean()).astype(int)  # Simulated failure

# Split data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Train model
model = RandomForestClassifier(n_estimators=100, random_state=42)
model.fit(X_train, y_train)

# Evaluate
y_pred = model.predict(X_test)
print('Model Accuracy:', accuracy_score(y_test, y_pred))