# -*- coding: utf-8 -*-
"""preprocessing

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sYX6kPX_F_EJS93wXBPbeuzx6GVRIDGg
"""

import pandas as pd

def load_data():
    """Load and preprocess the NASA CMAPSS dataset (FD001)."""
    df_train = pd.read_csv('data/train_FD001.txt', delim_whitespace=True, header=None)
    df_test = pd.read_csv('data/test_FD001.txt', delim_whitespace=True, header=None)
    df_rul = pd.read_csv('data/RUL_FD001.txt', delim_whitespace=True, header=None)

    # Assign column names
    cols = ["unit", "time", "op1", "op2", "op3"] + [f"sensor_{i}" for i in range(1, 22)]
    df_train.columns = cols
    df_test.columns = cols

    return df_train, df_test, df_rul

if __name__ == '__main__':
    df_train, df_test, df_rul = load_data()
    print(df_train.head())